INSERT INTO CLIENTE ("ENDERECO", "NOME", "TELEFONE") VALUES ('RJ', 'Hugo', '981819711');
INSERT INTO CLIENTE ("ENDERECO", "NOME", "TELEFONE") VALUES ('SP', 'Gustavo', '123456789');
INSERT INTO CLIENTE ("ENDERECO", "NOME", "TELEFONE") VALUES ('SP', 'Inacio', '678912345');

INSERT INTO PIZZA ("SABOR", "PRECO") VALUES ('Calabresa', '30');
INSERT INTO PIZZA ("SABOR", "PRECO") VALUES ('Mussarela', '25');
INSERT INTO PIZZA ("SABOR", "PRECO") VALUES ('Portuguesa', '35');
INSERT INTO PIZZA ("SABOR", "PRECO") VALUES ('Marguerita', '28');
INSERT INTO PIZZA ("SABOR", "PRECO") VALUES ('4 queijos', '30');





